---
- name: Report Application Load Balancers
  hosts: localhost
  gather_facts: no
  connection: local

  vars_files:
    - aws_credentials/aws_credentials.yml

  tasks:
    - name: Get list of all Application Load Balancers
      amazon.aws.elb_application_lb_info:
        # --- SSO MODE: Only include aws_profile when aws_mode is 'sso' ---
        aws_profile: "{{ aws_profile if aws_mode == 'sso' else omit }}"

        # --- STATIC MODE: Only include keys when aws_mode is 'static' ---
        # Note: If not using SSO, you MUST pass all three keys for session tokens
        access_key: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        secret_key: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        session_token: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"

        region: "{{ aws_region }}"
      register: alb_data

    - name: Display ALB Details
      ansible.builtin.debug:
        msg: "ALB Name: {{ item.load_balancer_name }} | ARN: {{ item.load_balancer_arn }} | DNS: {{ item.dns_name }} | Scheme: {{ item.scheme }} | State: {{ item.state.code }} | VPC: {{ item.vpc_id }}"
      loop: "{{ alb_data.load_balancers }}"
      loop_control:
        label: "{{ item.load_balancer_name }}"

    - name: Display ALB Traffic Details
      ansible.builtin.debug:
        msg: "ALB: {{ item.load_balancer_name }} | Type: {{ item.type }} | IP Address Type: {{ item.ip_address_type }} | Availability Zones: {{ item.availability_zones | map(attribute='zone_name') | join(', ') }} | Security Groups: {{ item.security_groups | join(', ') }}"
      loop: "{{ alb_data.load_balancers }}"
      loop_control:
        label: "{{ item.load_balancer_name }}"

    - name: Get listeners for each ALB
      amazon.aws.elb_application_lb_info:
        # --- SSO MODE: Only include aws_profile when aws_mode is 'sso' ---
        aws_profile: "{{ aws_profile if aws_mode == 'sso' else omit }}"

        # --- STATIC MODE: Only include keys when aws_mode is 'static' ---
        access_key: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        secret_key: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        session_token: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"

        load_balancer_arns:
          - "{{ item.load_balancer_arn }}"
        region: "{{ aws_region }}"
      loop: "{{ alb_data.load_balancers }}"
      register: alb_listeners_data
      loop_control:
        label: "{{ item.load_balancer_name }}"

    - name: Display ALB Listener Details
      ansible.builtin.debug:
        msg: "ALB: {{ item.0.load_balancer_name }} | Listener ARN: {{ item.1.listener_arn }} | Protocol: {{ item.1.protocol }} | Port: {{ item.1.port }} | SSL Policy: {{ item.1.ssl_policy | default('N/A') }} | Default Actions: {{ item.1.default_actions | map(attribute='type') | join(', ') }}"
      loop: "{{ alb_data.load_balancers | zip(alb_listeners_data.results) | list | subelements('1.load_balancers.0.listeners', skip_missing=True) }}"
      loop_control:
        label: "{{ item.0.load_balancer_name }}"
      when: item.1 is defined

    - name: Get target groups
      community.aws.elb_target_group_info:
        # --- SSO MODE: Only include aws_profile when aws_mode is 'sso' ---
        aws_profile: "{{ aws_profile if aws_mode == 'sso' else omit }}"

        # --- STATIC MODE: Only include keys when aws_mode is 'static' ---
        access_key: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        secret_key: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        session_token: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"

        region: "{{ aws_region }}"
      register: tg_data

    - name: Display Target Group Details
      ansible.builtin.debug:
        msg: "Target Group: {{ item.target_group_name }} | ARN: {{ item.target_group_arn }} | Protocol: {{ item.protocol }} | Port: {{ item.port }} | VPC: {{ item.vpc_id }} | Health Check Path: {{ item.health_check_path | default('N/A') }} | Target Type: {{ item.target_type }}"
      loop: "{{ tg_data.target_groups }}"
      loop_control:
        label: "{{ item.target_group_name }}"

    - name: Get CloudWatch metrics for ALB (RequestCount - Last Hour)
      amazon.aws.cloudwatch_metric_alarm_info:
        # --- SSO MODE: Only include aws_profile when aws_mode is 'sso' ---
        aws_profile: "{{ aws_profile if aws_mode == 'sso' else omit }}"

        # --- STATIC MODE: Only include keys when aws_mode is 'static' ---
        access_key: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        secret_key: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        session_token: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"

        region: "{{ aws_region }}"
      register: cw_alarms
      ignore_errors: yes

    - name: Get CloudWatch metrics using AWS CLI (RequestCount)
      ansible.builtin.command:
        cmd: >
          aws cloudwatch get-metric-statistics
          --namespace AWS/ApplicationELB
          --metric-name RequestCount
          --dimensions Name=LoadBalancer,Value={{ item.load_balancer_arn.split('/')[-3:] | join('/') }}
          --start-time {{ lookup('pipe', 'date -u -d "1 hour ago" +%Y-%m-%dT%H:%M:%S') }}
          --end-time {{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%S') }}
          --period 3600
          --statistics Sum
          --region {{ aws_region }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        AWS_SECRET_ACCESS_KEY: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        AWS_SESSION_TOKEN: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"
        AWS_PROFILE: "{{ aws_profile if aws_mode == 'sso' else omit }}"
      loop: "{{ alb_data.load_balancers }}"
      register: alb_request_count
      loop_control:
        label: "{{ item.load_balancer_name }}"
      ignore_errors: yes

    - name: Display ALB CloudWatch Metrics (RequestCount - Last Hour)
      ansible.builtin.debug:
        msg: "ALB: {{ item.item.load_balancer_name }} | Total Requests (Last Hour): {{ (item.stdout | from_json).Datapoints[0].Sum | default(0) | int }}"
      loop: "{{ alb_request_count.results }}"
      loop_control:
        label: "{{ item.item.load_balancer_name }}"
      when: item.stdout is defined and (item.stdout | from_json).Datapoints | length > 0

    - name: Get CloudWatch metrics using AWS CLI (TargetResponseTime)
      ansible.builtin.command:
        cmd: >
          aws cloudwatch get-metric-statistics
          --namespace AWS/ApplicationELB
          --metric-name TargetResponseTime
          --dimensions Name=LoadBalancer,Value={{ item.load_balancer_arn.split('/')[-3:] | join('/') }}
          --start-time {{ lookup('pipe', 'date -u -d "1 hour ago" +%Y-%m-%dT%H:%M:%S') }}
          --end-time {{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%S') }}
          --period 3600
          --statistics Average
          --region {{ aws_region }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        AWS_SECRET_ACCESS_KEY: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        AWS_SESSION_TOKEN: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"
        AWS_PROFILE: "{{ aws_profile if aws_mode == 'sso' else omit }}"
      loop: "{{ alb_data.load_balancers }}"
      register: alb_response_time
      loop_control:
        label: "{{ item.load_balancer_name }}"
      ignore_errors: yes

    - name: Display ALB CloudWatch Metrics (Response Time - Last Hour)
      ansible.builtin.debug:
        msg: "ALB: {{ item.item.load_balancer_name }} | Average Response Time (Last Hour): {{ (item.stdout | from_json).Datapoints[0].Average | default(0) | float | round(3) }} seconds"
      loop: "{{ alb_response_time.results }}"
      loop_control:
        label: "{{ item.item.load_balancer_name }}"
      when: item.stdout is defined and (item.stdout | from_json).Datapoints | length > 0

    - name: Get CloudWatch metrics using AWS CLI (HTTPCode_Target_2XX_Count)
      ansible.builtin.command:
        cmd: >
          aws cloudwatch get-metric-statistics
          --namespace AWS/ApplicationELB
          --metric-name HTTPCode_Target_2XX_Count
          --dimensions Name=LoadBalancer,Value={{ item.load_balancer_arn.split('/')[-3:] | join('/') }}
          --start-time {{ lookup('pipe', 'date -u -d "1 hour ago" +%Y-%m-%dT%H:%M:%S') }}
          --end-time {{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%S') }}
          --period 3600
          --statistics Sum
          --region {{ aws_region }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ static_aws_access_key if aws_mode == 'static' else omit }}"
        AWS_SECRET_ACCESS_KEY: "{{ static_aws_secret_key if aws_mode == 'static' else omit }}"
        AWS_SESSION_TOKEN: "{{ static_aws_session_token if aws_mode == 'static' else omit }}"
        AWS_PROFILE: "{{ aws_profile if aws_mode == 'sso' else omit }}"
      loop: "{{ alb_data.load_balancers }}"
      register: alb_2xx_count
      loop_control:
        label: "{{ item.load_balancer_name }}"
      ignore_errors: yes

    - name: Display ALB CloudWatch Metrics (2XX Count - Last Hour)
      ansible.builtin.debug:
        msg: "ALB: {{ item.item.load_balancer_name }} | 2XX Responses (Last Hour): {{ (item.stdout | from_json).Datapoints[0].Sum | default(0) | int }}"
      loop: "{{ alb_2xx_count.results }}"
      loop_control:
        label: "{{ item.item.load_balancer_name }}"
      when: item.stdout is defined and (item.stdout | from_json).Datapoints | length > 0